import pandas as pd
def hla_filter_framer(allele_exon_dict:dict, exon_numbers:list)->pd.DataFrame:
    '''This function creates a DataFrame from list generated by hla_parser and filters DataFrame by exon numbers'''
    exon_numbers = [int(exon_number) for exon_number in exon_numbers]
    df = pd.DataFrame(allele_exon_dict) # создаем датафрэйм
    df = df.loc[exon_numbers,].reset_index().drop(labels='index', axis=1) # сбрасываем индексы, для быстрой работы
    return df
